# Generated by Django 5.1 on 2024-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('MRP', models.CharField(max_length=255)),
                ('available_skus', models.CharField(max_length=255)),
                ('fit', models.CharField(max_length=255)),
                ('fabric', models.CharField(max_length=255)),
                ('neck', models.CharField(max_length=255)),
                ('sleeve', models.CharField(max_length=255)),
                ('pattern', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
    ]
